model:
  name: "Qwen/Qwen3-1.7B"
  max_seq_length: 1400
  dtype: float16

data_prep:
  combine_clean_train_complete: true
  combine_clean_validation_complete: true
  extract_required_train_and_golden_complete: true
  extract_required_validation_complete: true

dataset:
  train_path: "data/processed/training_dataset.json"
  validation_path: "data/processed/validation_dataset.json"
  golden_path: "data/processed/golden_dataset.json"
  train_size: 20000
  validation_size: 2000
  golden_size: 400
  raw_train_folder: "data/raw/training"
  raw_validation_folder: "data/raw/validation"
  raw_combined_train_path: "data/raw/training/summary_training.json"
  raw_combined_validation_path: "data/raw/validation/summary_validation.json"

quantization:
  load_in_4bit: true
  quant_type: "nf4"
  compute_dtype: "float16"
  use_double_quant: true

lora:
  r: 16
  alpha: 32
  dropout: 0.05
  bias: "none"
  task_type: "CAUSAL_LM"
  target_modules: [q_proj, v_proj]

training:
  epochs: 1
  batch_size: 4
  learning_rate: 0.0002
  gradient_accumulation_steps: 4
  max_train_samples: 400
  max_validation_samples: 100
  bf16: false
  fp16: false
  logging_steps: 1
  optim: adamw_torch
  gradient_checkpointing: true
  dataloader_pin_memory: true
  report_to: "none"
  resume_from_checkpoint: true

evaluation:
  strategy: "steps"
  eval_steps: 5
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

checkpoint:
  output_dir: "checkpoints"
  save_strategy: "steps"
  save_steps: 5
  save_total_limit: 5

generation:
  max_new_tokens: 150